### ISSUE TITLE
求助！编译面上项目申请书时遇见编译错误

### ISSUE THREAD

**Issue by TsinghuaDong** [huangwb8/ChineseResearchLaTeX#1]
主要是这部分：ChineseResearchLaTeX/NSFC_General/main.tex:286: Incomplete \iffalse; all text was ignored after line 95.
<inserted text> 
                \fi 
l.286 \include{extraTex/1.1.立项依据.tex}

稍完整一点的报错：
Package fontspec Warning: Font "FandolKai-Regular" does not contain requested
(fontspec)                Script "CJK".

[1] (./extraTex/1.1.立项依据.tex

LaTeX Warning: Citation `John1997' on page 2 undefined on input line 8.

LaTeX Warning: Reference `zzmx-116' on page 2 undefined on input line 10.

LaTeX Warning: Reference `zzmx-mobile-105' on page 2 undefined on input line 23.

[2] (c:/texlive/2021/texmf-dist/tex/latex/wasysym/uwasy.fd)

LaTeX Font Warning: Font shape `U/wasy/m/n' in size <5.5> not available
(Font)              size <5> substituted on input line 33.

(c:/texlive/2021/texmf-dist/tex/latex/amsfonts/umsa.fd) (c:/texlive/2021/texmf-dist/tex/latex/amsfonts/umsb.fd) [3])
c:/Users/EnhuanDong/Documents/Seafile/DehDatabase/项目/国自然面上（筹）/NSFC-body/ChineseResearchLaTeX/NSFC_General/main.tex:286: Incomplete \iffalse; all text was ignored after line 95.
<inserted text> 
                \fi 
l.286 \include{extraTex/1.1.立项依据.tex}

**Comment by TsinghuaDong** [comment]
我用的就是xelatex方式编译的，参考的https://blognas.hwb0307.com/skill/5762，也没有改模板。。。不知道怎么回事

**Comment by TsinghuaDong** [comment]
这个项目我能编译起来：Ruzim/NSFC-application-template-latex.git

**Comment by huangwb8** [comment]
@TsinghuaDong 

之前有个小伙伴也问题。 按以下步骤逐步排障：

1. 按照[Latex问题解决1：报错Incomplete \iffalse； all text was ignored after line 20. ＜inserted text＞\_incomplete \ifx; all text was ignored after line 1-CSDN博客](https://blog.csdn.net/qq_42974034/article/details/128585915)排障。
2. 尝试将texlive升级至2022年3月份或更新的版本。 我的本地版本为Tex Live 2022。
3. 如果反复折腾均不可用，请暂时尝试[fylimas/nsfc](https://github.com/fylimas/nsfc)。

祝好！

**Comment by TsinghuaDong** [comment]
感谢，我再试试

> @TsinghuaDong
> 
> 之前有个小伙伴也问题。 按以下步骤逐步排障：
> 
> 1. 按照[Latex问题解决1：报错Incomplete \iffalse； all text was ignored after line 20. ＜inserted text＞_incomplete \ifx; all text was ignored after line 1-CSDN博客](https://blog.csdn.net/qq_42974034/article/details/128585915)排障。
> 2. 在`main.tex`中，对于`{\input{extraTex/2.3.承担项目.tex}}`之类的代码,将最外面的括号去除，改为类似这样：`\input{extraTex/2.3.承担项目.tex}`。
> 3. 尝试将texlive升级至2022年3月份或更新的版本。 我的本地版本为Tex Live 2022。
> 4. 如果反复折腾均不可用，请暂时尝试[fylimas/nsfc](https://github.com/fylimas/nsfc)。
> 
> 祝好！

**Comment by huangwb8** [comment]
@TsinghuaDong 

大锅，这个问题解决了嘛 (～￣▽￣)～
