### ISSUE TITLE
中山大学研究生论文模板

### ISSUE THREAD

**Issue by 1FCENdoge** [huangwb8/ChineseResearchLaTeX#2]
中山大学有一个研究生论文模板，不知道行不行，硕士和博士应该是通用的。[中山大学研究生学位论文LaTeX模板（试用）](https://github.com/1FCENdoge/SYSUThesis)

**Comment by huangwb8** [comment]
谢谢提醒～我之前写博士论文的时候改过一个模版，我已经顺利毕业了。我的计划里有这个，就是我想公布那个被我证实可用的中山大学博士毕业的latex模版。
