### ISSUE TITLE
将参考文献号设为上标，并加方括号！

### ISSUE THREAD

**Issue by yyf17** [huangwb8/ChineseResearchLaTeX#3]
我使用的是地区基金模版，发现参考文献都没有上标。

**Comment by huangwb8** [comment]
不好意思，刚刚看到 ~ 

您可以使用natbib包进行设置。 比如，添加如下命令：

```
% 参考文献上标与压缩
\usepackage[super,square,comma,sort&compress]{natbib}
```

我添加的位置在这里：（在`\documentclass`...`\end{document}`之间，然后在正文开始前即可）

![image](https://github.com/huangwb8/ChineseResearchLaTeX/assets/35643122/8a27f614-0a1d-4899-adca-200b55032490)

参考文献的标识如下：

![image](https://github.com/huangwb8/ChineseResearchLaTeX/assets/35643122/3d97bc23-5be3-46c5-9615-2f31c97374ad)

希望这个回答不要太迟哈！ 

另外，这个设置并不是常规需要的，所以我没有在模板里正式更新。 请按需食用！
