### ISSUE TITLE
MacOS系统上，节的数字编号不是楷体，请问该怎么解决？

### ISSUE THREAD

**Issue by XiaosuWang** [huangwb8/ChineseResearchLaTeX#5]
尊敬的作者，您好，我使用了您的模板进行撰写青基标书，但是是在macos系统上，其他一切编译正常，只有subsection以及更小的标题中，数字部分好像显示的不是楷体，请问该怎么解决？
下图中左边是我在MacOS上生成的，右边是您模板中自带的PDF中的效果：
<img width="540" alt="截屏2024-03-08 17 47 53" src="https://github.com/huangwb8/ChineseResearchLaTeX/assets/36366980/1afc2263-68a8-4ff0-9f72-fef42c2f9598">

**Comment by XiaosuWang** [comment]
已解决！
解决办法，使用下面链接（https://github.com/fylimas/nsfc/tree/main/fonts）中提供的Kaiti.ttf即可。

**Comment by huangwb8** [comment]
@XiaosuWang  

好的 ~ 其实也可以换为MacOS的楷体，只是它的写法和Win不一样。 

加油，祝高中！
