### ISSUE TITLE
请问怎么在研究基础章节添加自己的已发表文献？

### ISSUE THREAD

**Issue by wsstriving** [huangwb8/ChineseResearchLaTeX#6]
再次感谢作者的模板，想问一下如果要在研究基础处添加自己的发表文献的话，是按照参考文献来么？

**Comment by huangwb8** [comment]
我觉得可以类似这样 ：

```
1. 本人以第一作者在XX杂志上发表论文（Huang, 2018）\cite{huang2018}。
2. 本人2018年以第一作者在XX杂志上发表论文（DOI：xxx）。
```

由于我在前面的内容已经数次插入自己的文献，所以我在研究基础上就采用了第2种方法。

基本原则：**方便专家知道你前期发表成果的level和新旧程度即可**。
