### ISSUE TITLE
font

### ISSUE THREAD

**Issue by Technew94** [huangwb8/ChineseResearchLaTeX#7]
Huang老师您好，
请问1.1和1.2
\begin{enumerate}
    \item \itemtitlefont{项目1}：\ssssubtitle{1}快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。\ssssubtitle{2}快乐 快乐。快乐 快乐。快乐 。快乐 快乐（图\ref{zzmx-mobile-105}） 。
    \item \itemtitlefont{项目2}：快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。快乐 快乐。
\end{enumerate}
\begin{tabular}{lllll}
\lstinputlisting[style=codestyle01, language=Bash]{code/test.sh}

这三处都亮黄色，分别提示
LaTeX Font: Font shape `OMS/TimesNewRoman(0)/m/n' undefined
(Font)	using `OMS/cmsy/m/n' instead.LaTeX
LaTeX Font: Font shape `U/wasy/m/n' in size <5.5> not available
(Font)	size <5> substituted.LaTeX
LaTeX Font: Font shape `TU/tnr/m/n' undefined
(Font)	using `TU/lmr/m/n' instead.LaTeX 
可以理解为字体的问题吗？
请问该如何修正呢？
烦请不吝赐教，多谢

**Comment by huangwb8** [comment]
@Technew94 

是否方便提供一些额外的信息，比如：

+ 操作系统: Windows？ Mac？ Linux？
+ LaTex版本：texlive？还是其它
+ 测试环境：VSCode？还是其它方案？
